### ISSUE TITLE
Unable to run tests after configuring django-structlog

### ISSUE THREAD

**Issue by lewoudar** [jrobichaud/django-structlog#292]
Hello everyone, 
I followed the [Getting Started](https://django-structlog.readthedocs.io/en/latest/getting_started.html) documentation and I ended up with this configuration

```python
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json_formatter': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.processors.JSONRenderer(),
        },
        'plain_console': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.dev.ConsoleRenderer(),
        },
        'key_value': {
            '()': structlog.stdlib.ProcessorFormatter,
            'processor': structlog.processors.KeyValueRenderer(key_order=['timestamp', 'level', 'event', 'logger']),
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'plain_console',
        },
        'json_file': {
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': 'logs/json.log',
            'formatter': 'json_formatter',
        },
        'flat_line_file': {
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': 'logs/flat_line.log',
            'formatter': 'key_value',
        },
    },
    'loggers': {
        'django_structlog': {
            'handlers': ['console', 'flat_line_file', 'json_file'],
            'level': 'INFO',
        },
        'my_project_name': {
            'handlers': ['console', 'flat_line_file', 'json_file'],
            'level': 'INFO',
        },
    },
}

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)
```

When running the application with `python manage.py runserver` I don't have errors (although I can't see my custom log messages, but this is another story/issue)

But when I run my tests I have this error

```python
Traceback (most recent call last):
  File "C:\Users\KevinTEWOUDA\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 573, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 758, in configure_handler
    result = factory(**kwargs)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\Programs\Python\Python311\Lib\logging\handlers.py", line 479, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "C:\Users\KevinTEWOUDA\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\KevinTEWOUDA\\PycharmProjects\\python\\alpharezo_api\\monitoring\\tests\\logs\\flat_line.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.1.4\plugins\python\helpers\pycharm\_jb_pytest_runner.py", line 60, in <module>
    sys.exit(pytest.main(args, plugins_to_load + [Plugin]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_callers.py", line 130, in _multicall
    teardown[0].send(outcome)
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\_pytest\helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 1327, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_callers.py", line 152, in _multicall
    return outcome.get_result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pytest_django\plugin.py", line 353, in pytest_load_initial_conftests
    _setup_django()
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\pytest_django\plugin.py", line 236, in _setup_django
    django.setup()
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\django\__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "C:\Users\KevinTEWOUDA\AppData\Local\pypoetry\Cache\virtualenvs\alpharezo-api-KKCfMTX3-py3.11\Lib\site-packages\django\utils\log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "C:\Users\KevinTEWOUDA\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "C:\Users\KevinTEWOUDA\AppData\Local\Programs\Python\Python311\Lib\logging\config.py", line 580, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'flat_line_file'
```

I'm using pytest and pytest-django to run my tests, I try to write a conftest.py following the recommendations in [structlog](https://www.structlog.org/en/stable/testing.html) documentation

````python
import pytest
import structlog
from structlog.testing import LogCapture


@pytest.fixture()
def log_output():
    return LogCapture()


@pytest.fixture(autouse=True)
def fixture_configure_structlog(log_output):
    structlog.configure(processors=[log_output])
```

Do you have any idea of what I did wrong?

Environment
- pytest 7.4.0
- django 4.2.4
- pytest-django 4.5.2
- django-structlog 5.3.0

**Comment by jrobichaud** [comment]
I see you used the examples logger handlers from the doc, you might want to use something adapted to your project.

Does a ˋlog` folder exist?

**Comment by lewoudar** [comment]
I created a local log folder to make it work in *live tests*.

**Comment by jrobichaud** [comment]
Sorry, I meant `logs`.

**Comment by jrobichaud** [comment]
The error:

```

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\KevinTEWOUDA\\PycharmProjects\\python\\alpharezo_api\\monitoring\\tests\\logs\\flat_line.log'
```
Make sure this path can exist.

**Comment by jrobichaud** [comment]
But do you really need to output into files? 

You could only output in the console.

**Comment by lewoudar** [comment]
Not really, I think it will serve for production
But do you know if I can remove file configuration for testing?

**Comment by jrobichaud** [comment]
Yes, either add conditions in your config file or make different config files.

See django documentation about this: https://docs.djangoproject.com/en/4.2/topics/settings/

**Comment by lewoudar** [comment]
Ok, thanks, removing file configuration fixes the problem. I think I can close this issue.

**Comment by jrobichaud** [comment]
If you use a  FileHandler you might saturate the disk space of your server.

You might want to take a look at the different python handlers (or implement your own).

Consider RotatingFileHandler.


https://docs.python.org/3/library/logging.handlers.html

**Comment by lewoudar** [comment]
Ok, thanks for the advice!
