### ISSUE TITLE
Double exception logging on console

### ISSUE THREAD

**Issue by pawel-steto** [jrobichaud/django-structlog#483]
Hello, 

Thank you for this amazing project !
I am trying to improve the DX on my django app and I have an issue with logging exceptions. 
Here is my minimal configuration:

```python
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "plain_console": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
    },
    "handlers": {
        "main": {
            "class": "logging.StreamHandler",
            "formatter": "plain_console",
        },
    },
    "loggers": {
        "root": {
            "handlers": ["main"],
            "level": "INFO",
        },
    },
}

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ],
    logger_factory=structlog.stdlib.LoggerFactory(),
    cache_logger_on_first_use=True,
)
```

This is the log ouput on the console when doing a successful API call:

```
web-1  | 2024-03-12T10:17:57.969699Z [info     ] request_started                [django_structlog.middlewares.request] ip=192.168.65.1 request=GET /healthcheck/db request_id=bfa67622-3ed5-47b8-9266-d9f4ea095755 user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0 user_id=None
web-1  | 2024-03-12T10:17:57.979702Z [info     ] request_finished               [django_structlog.middlewares.request] code=200 ip=192.168.65.1 request=GET /healthcheck/db request_id=bfa67622-3ed5-47b8-9266-d9f4ea095755 user_id=None
web-1  | [12/Mar/2024 10:17:57] "GET /healthcheck/db HTTP/1.1" 200 0
```
This correct but I still have the last line from django.

The bigger issue is when an exception occur:
```
web-1  | 2024-03-12T10:20:00.893646Z [info     ] request_started                [django_structlog.middlewares.request] ip=192.168.65.1 request=GET /healthcheck/api request_id=b0c2f1ad-8f21-402d-aaf8-f3996a55a27a user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0 user_id=None
web-1  | 2024-03-12T10:20:00.895065Z [error    ] request_failed                 [django_structlog.middlewares.request] code=500 ip=192.168.65.1 request=GET /healthcheck/api request_id=b0c2f1ad-8f21-402d-aaf8-f3996a55a27a user_id=None
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
[TRUNCATED]
web-1  | ZeroDivisionError: division by zero
web-1  | Internal Server Error: /healthcheck/api
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
web-1  |     response = get_response(request)
[TRUNCATED]
web-1  | ZeroDivisionError: division by zero
web-1  | Internal Server Error: /healthcheck/api
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
web-1  |     response = get_response(request)
[TRUNCATED]
web-1  | ZeroDivisionError: division by zero
web-1  | [12/Mar/2024 10:20:00] "GET /healthcheck/api HTTP/1.1" 500 105241
```

As you can see the exception is logged 3 times.

My questions are:
1. Can I disable completely django logger ? If yes, how and should this be done ?
2. Can I disable the django logger on prod ? Is there some log that I will miss if I do so ?

How would you tackle this issue ?

**Comment by jrobichaud** [comment]
# 1. Can I disable completely django logger ? If yes, how and should this be done ? 

I just tried it myself and found three solutions but not sure if they are the bests in your situation.

I had trouble to override django loggers for a reason I ignore. I think its because they are already configured when I try to configure them.

The root logger catches everything from every loggers. You could either:
	1. whitelist: disable the root logger and make sure to whitelist every logger you need. Ex: https://github.com/jrobichaud/django-structlog/issues/274#issuecomment-1655917569
   2. whitelist: reconfigure everything by set `'disable_existing_loggers': True,`. similar to the previous one
   3. blacklist: leave it like this but implement a custom filter See below "Custom Filter":


## Custom filter
```python
import logging

import structlog
from structlog import DropEvent
from structlog.typing import EventDict

def filter_django_logs(
    logger: logging.Logger, method_name: str, event_dict: EventDict
) -> EventDict:
    # Customize it like you want
    if logger.name == "django" or logger.name == "django.server":
        raise DropEvent
    return event_dict


structlog.configure(
    processors=[
        filter_django_logs,
		# ....
```

# 2. Can I disable the django logger on prod ? Is there some log that I will miss if I do so ?

I am not aware of any issues about not logging django requests.

I would be interested to see if people have different opinions.

**Comment by jrobichaud** [comment]
@pawel-steto, its weird, I am still getting the django logs with your configuration unless I set this:

```
    "disable_existing_loggers": True,
```

**Comment by jrobichaud** [comment]
also the config you shared is incomplete, `json_formatter` is not defined.
